### ISSUE TITLE
Issues with Local Admin on Win10

### ISSUE THREAD

**Issue by dirtdiver512** [awsmhacks/CrackMapExtreme#9]
Having issues with any administrative command being ran against a Win10 system joined to a domain or not using a local admin account.  Works fine if I use a domain account with local admin, but not a local account with local admin.  I get the below error and yes i verified the aacount is in the local admin group:

 cmx  smb 172.16.1.217 -u user-p password --local-auth  --exec-method smbexec -x "dir c:\\"

Unable to execute, user must have local admin privileges

**Comment by awsmhacks** [comment]
@dirtdiver512  I was able to reproduce this. The issue is with Remote UAC.  
  
You need a registry key at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System. 
called LocalAccountTokenFilterPolicy.   
Set its value to 1   
  
After creating the key and setting it to 1, open up services and restart the 'Server' service.

**Comment by awsmhacks** [comment]
Top is before setting that key, bottom is after
![image](https://user-images.githubusercontent.com/2059326/65732660-82730800-e090-11e9-9dcc-151f6735a464.png)

**Comment by awsmhacks** [comment]
I think I'll add a command tomorrow to enable that key and restart the service (will need to be done from an account that can auth as admin though.  i.e. - the domain account with localadmin)

**Comment by dirtdiver512** [comment]
yeah that was it, not sure how i missed that thanks!......a script would be awesome.

**Comment by awsmhacks** [comment]
1. first, localadmin isnt showing as admin,   
2. then querys the uac status --uac-status    
3. then updates the reg keys --uac  
4. then restart the lanmanservice --stop-service  
5. finally, can login with localadmin!  
![image](https://user-images.githubusercontent.com/2059326/65806882-7ac76800-e151-11e9-9eca-16cb26c5dfbb.png)
  
I think ill make a function that does all the steps too!

**Comment by awsmhacks** [comment]
=== check enableLUA and LocalAccountTokenFilterPolicy  ===   
-uac-status        
    
*  I still need to add some context but basically you want enableLUA set to 0 and localaccount set to 1  
  
  
=== creates/sets both keys to what we want ===    
-uac                
  
Then you just need to restart the lanmanservice with  
--stop-service  
  (it defaults to the lanmanservice for now, gonna extend later for other services)
